Localization.define(:es_MX) do |l|
  # layout
  l.store 'Search', 'Buscar'
  l.store 'Index', 'Índice'
  l.store 'Advanced search', 'Búsqueda avanzada'
  l.store 'Most cited authors', 'Autores más citados'
  
  l.store 'Development', 'Desarrollo'
  l.store 'Sponsors', 'Patrocinadores'
  l.store 'Contact', 'Contacto'
  l.store 'Team', 'Equipo'
  l.store 'About', 'Acerca de'
  
  # Listings
  l.store 'Results', 'Resultados'
  l.store 'Cited by %d', 'Citado por %d'
  l.store 'New Search', 'Nueva Búsqueda'
  l.store '%d articles citing', ['Artículo que cita a', '%d artículos que citan a']
  l.store 'Previous', 'Anterior'
  l.store 'Next', 'Siguiente'
  
  # Titles
  l.store 'Articles writen by %s', 'Artículos de %s'
  
  # Messages
  l.store 'Your search "%s" did not match any articles', 'La consulta "%s" no ha obtenido ningún artículo como resultado.'
  
  l.store 'ranking', 'posición'
  l.store 'name', 'nombre'
  l.store 'citations', 'citaciones'
  l.store 'probable <br/> self-citations', 'auto-citaciones <br/> probables'
  
  # About text
  l.store 'Scielo Index is a citation search engine for documents and articles ' + 
          ' from the virtual library %s, which contains the most important journals of the country',
          'Scielo Index es un buscador de referencias y' + 
          ' citas a documentos y artículos a partir de los acervos de la hemeroteca' +
          ' virtual %s, que incorpora a las revistas de investigación más importantes del país.'
          
  l.store 'With SciELO Index the user will find citations of documents by author name, title, keywords,' +
          ' and any combination of those. The system can also generate PDF reports of the found citations.',
          'En SciELO Index el usuario podrá encontrar las citas a documentos a partir de diferentes puntos de acceso:' +
          ' nombre del autor, título del artículo o documento, o palabras incluidas en el título del artículo o documento,' +
          ' así como mediante una búsqueda combinada de estas tres opciones. El sistema genera reportes en formato PDF de' +
          ' las citas y referencias localizadas.'
                  
  l.store 'SciELO Index is being developed and mantained by the Dirección General de Bibliotecas of the Universidad Nacional' +
          ' Autónoma de México (UNAM), with the sponsorship from the Macroproyecto Tecnologías para la Universidad de la' +
          ' Información y la Computación.',
          'SciELO Index es desarrollado y mantenido por la Dirección General de Bibliotecas de la Universidad Nacional' +
          ' Autónoma de México (UNAM), con apoyo del Macroproyecto Tecnologías para la Universidad de la Información y' +
          ' la Computación.'
          
  # Advanced Search
  l.store 'Title', 'Título'
  l.store 'is exactly', 'es exactamente'
  l.store 'with at least one of the words', 'con al menos una de las palabras'
  l.store 'with exact phrase', 'con la frase exacta'
  
  l.store 'Journal', 'Revista'
  l.store 'Match articles published in', 'Mostrar artículos publicados en'
  
  l.store 'Author', 'Autor'
  l.store 'Match any articles written by', 'Mostrar artículos escritos por'
  
  # PDF Reports
  
  l.store 'Citation report', 'Informe de citas'
  l.store 'This document was automatically generated by SciELOIndex', 'Éste documento fue generado automáticamente por SciELOIndex'
  
end