Localization.define(:es_MX) do |l|
  # layout
  l.store 'Search', 'Buscar'
  l.store 'Home', 'Inicio'
  l.store 'Advanced search', 'Búsqueda avanzada'
  l.store 'Most cited authors', 'Autores más citados'
  
  l.store 'Development', 'Desarrollo'
  l.store 'Sponsors', 'Patrocinadores'
  l.store 'Contact', 'Contacto'
  l.store 'Team', 'Equipo'
  l.store 'About', 'Acerca de'
  
  # Listings
  l.store 'Results', 'Resultados'
  l.store 'Searched for %s.', 'Busqueda de %s.'
  l.store 'Results %d to %d of %d', 'Resultados %d a %d de %d'
  l.store ' and', ' y'
  l.store 'Cited by %d', 'Citado por %d'
  l.store 'New Search', 'Nueva Búsqueda'
  l.store '%d articles citing', ['Artículo que cita a', '%d artículos que citan a']
  l.store 'Previous', 'Anterior'
  l.store 'Next', 'Siguiente'
  
  # Titles
  l.store 'Articles writen by %s', 'Artículos escritos por %s'
  
  # Messages
  l.store 'Your search "%s" did not match any articles', 'La consulta "%s" no ha obtenido ningún artículo como resultado.'
  
  l.store 'ranking', 'posición'
  l.store 'name', 'nombre'
  l.store 'citations', 'citaciones'
  l.store 'probable <br/> self-citations', 'auto-citaciones <br/> probables'
  
  # About text
  l.store 'Scielo Index is a citation search engine for documents and articles ' + 
          ' from the virtual library %s, which contains the most important journals of the country',
          'Scielo Index es un buscador de referencias y' + 
          ' citas a documentos y artículos a partir de los acervos de la hemeroteca' +
          ' virtual %s, que incorpora a las revistas de investigación más importantes del país.'
          
  l.store 'With SciELO Index the user will find citations of documents by author name, title, keywords,' +
          ' and any combination of those. The system can also generate PDF reports of the found citations.',
          'En SciELO Index el usuario podrá encontrar las citas a documentos a partir de diferentes puntos de acceso:' +
          ' nombre del autor, título del artículo o documento, o palabras incluidas en el título del artículo o documento,' +
          ' así como mediante una búsqueda combinada de estas tres opciones. El sistema genera reportes en formato PDF de' +
          ' las citas y referencias localizadas.'
                  
  l.store 'SciELO Index is being developed and mantained by the Dirección General de Bibliotecas of the Universidad Nacional' +
          ' Autónoma de México (UNAM), with the sponsorship from the Macroproyecto Tecnologías para la Universidad de la' +
          ' Información y la Computación.',
          'SciELO Index es desarrollado y mantenido por la Dirección General de Bibliotecas de la Universidad Nacional' +
          ' Autónoma de México (UNAM), con apoyo del Macroproyecto Tecnologías para la Universidad de la Información y' +
          ' la Computación.'
          
  # Advanced Search
  l.store 'Title', 'Título'
  l.store 'is exactly', 'es exactamente'
  l.store 'with at least one of the words', 'con al menos una de las palabras'
  l.store 'with exact phrase', 'con la frase exacta'
  
  l.store 'Journal', 'Revista'
  l.store 'Match articles published in', 'Mostrar artículos publicados en'
  
  l.store 'Author', 'Autor'
  l.store 'Match any articles written by', 'Mostrar artículos escritos por'
  l.store 'Any', 'Cualquiera'
  
  # PDF Reports
  
  l.store 'Citation report', 'Informe de citas'
  l.store 'This document was automatically generated by SciELOIndex', 'Éste documento fue generado automáticamente por SciELOIndex'
  
  # Administration
  
  l.store 'Welcome to the management and monitoring application for ScieloIndex', 'Bienvenido al portal de monitoreo y administración de ScieloIndex'
  l.store 'Loaded Data Explorer', 'Explorador de Datos Almacenados'
  l.store 'ScieloIndex Management', 'Administración de ScieloIndex'
  l.store 'Please, select any of the options listed in the menu', 'Por favor, selecciona alguna de las opciones listadas en el menú'
  l.store 'View Related Graph', 'Ver Gráfica Relacionada'
  l.store 'Author-Institution Results', 'Resultados Autor-Institución'
  l.store 'Article-Subject Results', 'Resultados Artículo-Disciplina'
  l.store 'General Results', 'Resultados Generales'
  l.store 'Articles and subjects', 'Artículos y disciplinas'
  l.store 'Authors and institutions', 'Autores e Instituciones'  
  l.store 'Subjects', 'Disciplinas'
  l.store 'Articles', 'Artículos'
  l.store 'Collections' , 'Colecciones'
  l.store 'Keywords' , 'Palabras Clave'
  l.store 'Institutions' , 'Instituciones'
  l.store 'Journals' , 'Journal'
  l.store 'Citations' , 'Citaciones'
  l.store 'Authors' , 'Autores'
  l.store 'Back', 'Atrás'
  l.store 'Migrate ScieloIndex data', 'Migrar datos de ScieloIndex'
  l.store 'Number of Journals', 'Número de Revistas'
  l.store 'Number of Issues', 'Número de Issues'
  l.store 'Number of Articles', 'Número de Artículos'
  l.store 'Number of Authors', 'Número de Autores'
  l.store 'Number of Journal References', 'Número de Referencias a Revistas'
  l.store 'Number of Issue References', 'Número de Referencias a Issues'
  l.store 'Number of Article References', 'Número de Referencias a Artículos'
  l.store 'Number of Author References', 'Número de Referencias a Autores'
  l.store 'Number of Citations', 'Número de Citaciones'
  l.store 'Migration in process...', 'Migración en proceso...'
  
  
  
  
end