# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

namespace :scielo do
  
  namespace :migrator do
    
    desc "Runs the scielo migrator."
    task :run => ["db:drop", "db:migrate"] do
      exec './tools/Migrator/migrator.rb'
    end
  
  end
end