# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

namespace :scielo do
  desc "Reset the postgres database"
  task :resetdb do
    `dropdb -U scielo scielo_development`
    `createdb -U scielo scielo_development`
    `sh -c 'cd db && psql -U scielo scielo_development < index.sql'`
  end
  
  desc "Runs the scielo migrator."
  task :migrate => :resetdb do
    `./tools/Migrator/migrator.rb`
  end
  
end