class ScieloIndexReport < TCPDF
  
  def initialize(orientation='P', unit='mm', format='letter')
     super
     # @ic ||= Iconv.new('ISO-8859-15', 'UTF-8')
     AddPage();
     SetFont('vera', '', 10)
     SetCreator('SciELO Index')
  end
  
  def SetAuthorInfo(info)
    @auth = info
  end
  
  def Title
    SetFont('vera', '', 20)
    Cell(0,0,_("Citation report"),0,0,"C")
    Ln(10)
    Cell(0,0,"#{@auth[:name]}",0,0,"C")
    Ln(15)
  end
  
  def ErrorReportTitle
    SetFont('vera', '', 20)
    Cell(0,0,_("Migrator Errors report"),0,0,"C")
    Ln(15)
  end
  
  def Header
    Image("#{File.join(RAILS_ROOT, 'public')}/images/logo_noalpha.png", 10, 10, 0, 20) 
    Image("#{File.join(RAILS_ROOT, 'public')}/images/logo_unam_noalpha.png", 160, 13, 0, 15) 
    Image("#{File.join(RAILS_ROOT, 'public')}/images/logo_dgb_noalpha.png", 175, 13, 0, 15)
    Ln(30)
  end
  
  def Footer
    SetFont('vera', '', 8)
    SetY(-15)
    SetX(15)
    Cell(0,5,_("This document was generated by SciELOIndex")) 
    SetY(-15)
    SetX(-30)
    SetFont('vera', 'B', 10)
    SetTextColor(0,0,200)
    Cell(0,5,"#{@auth[:name]}",0,0,"R",0,"http://dev.scielo.unam.mx:300/citation_index/list_authors_articles/#{@auth[:id]}") if @auth
  end
end