class ScieloIndexReport < FPDF
  
  def initialize(orientation='P', unit='mm', format='letter')
     super
     @ic ||= Iconv.new('ISO-8859-15', 'UTF-8')
     AddPage();
     SetFont('Arial', '', 10)
  end
  
  def SetAuthorInfo(info)
    @auth = info.split(":")
  end
  
  def Title
    SetFont('Arial', '', 20)
    Cell(0,0,"Citation List",0,0,"C")
    Ln(10)
    Cell(0,0,"#{@auth[0]}",0,0,"C")
    Ln(20)
  end
  
  def Header
    Image("#{File.join(RAILS_ROOT, 'public')}/images/logo_small.png", 10, 10, 0, 20) 
    Image("#{File.join(RAILS_ROOT, 'public')}/images/logo_unam_noalpha.png", 160, 13, 0, 15) 
    Image("#{File.join(RAILS_ROOT, 'public')}/images/logo_dgb_noalpha.png", 175, 13, 0, 15)
    Ln(30)
  end
  
  def Footer
    SetFont('Arial', '', 8)
    SetY(-15)
    SetX(15)
    Cell(0,5,"This document was generated by ScieloIndex") 
    SetY(-15)
    SetX(-30)
    SetFont('Arial', 'B', 10)
    SetTextColor(0,0,200)
    Cell(0,5,"#{@auth[0]}",0,0,"R",0,"http://dev.scielo.unam.mx:300/cite_index/find_auxiliar/#{@auth[1]}?cites=#{@auth[2]}") 
  end
  
  # ISO-8859-15 convertion to UTF-8
  def Cell(w,h=0,txt='',border=0,ln=0,align='',fill=0,link='')
    # these quotation marks are not correctly rendered in the pdf
    txt = txt.gsub(/[“”]/, '"') if txt
    txt = begin
      # 0x5c char handling
      txtar = txt.split('\\')
      txtar << '' if txt[-1] == ?\\
      txtar.collect {|x| @ic.iconv(x)}.join('\\').gsub(/\\/, "\\\\\\\\")
    rescue
      txt
    end || ''
    super w,h,txt,border,ln,align,fill,link
  end
  
  def MultiCell(w,h,txt,border=0,align='J',fill=0)
    # these quotation marks are not correctly rendered in the pdf
    txt = txt.gsub(/[“”]/, '"') if txt
    txt = begin
      # 0x5c char handling
      txtar = txt.split('\\')
      txtar << '' if txt[-1] == ?\\
      txtar.collect {|x| @ic.iconv(x)}.join('\\').gsub(/\\/, "\\\\\\\\")
    rescue
      txt
    end || ''
    super w,h,txt,border,align,fill
  end
end