INSERT INTO countries VALUES (004, 'Afganistán', 'AF');
INSERT INTO countries VALUES (248, 'Islas Åland', 'AX');
INSERT INTO countries VALUES (008, 'Albania', 'AL');
INSERT INTO countries VALUES (276, 'Alemania', 'DE');
INSERT INTO countries VALUES (020, 'Andorra', 'AD');
INSERT INTO countries VALUES (024, 'Angola', 'AO');
INSERT INTO countries VALUES (660, 'Anguilla', 'AI');
INSERT INTO countries VALUES (010, 'Antártida', 'AQ');
INSERT INTO countries VALUES (028, 'Antigua y Barbuda', 'AG');
INSERT INTO countries VALUES (530, 'Antillas Neerlandesas', 'AN');
INSERT INTO countries VALUES (682, 'Arabia Saudí', 'SA');
INSERT INTO countries VALUES (012, 'Argelia', 'DZ');
INSERT INTO countries VALUES (032, 'Argentina', 'AR');
INSERT INTO countries VALUES (051, 'Armenia', 'AM');
INSERT INTO countries VALUES (533, 'Aruba', 'AW');
INSERT INTO countries VALUES (036, 'Australia', 'AU');
INSERT INTO countries VALUES (040, 'Austria', 'AT');
INSERT INTO countries VALUES (031, 'Azerbaiyán', 'AZ');
INSERT INTO countries VALUES (044, 'Bahamas', 'BS');
INSERT INTO countries VALUES (048, 'Bahréin', 'BH');
INSERT INTO countries VALUES (050, 'Bangladesh', 'BD');
INSERT INTO countries VALUES (052, 'Barbados', 'BB');
INSERT INTO countries VALUES (112, 'Belarús', 'BY');
INSERT INTO countries VALUES (056, 'Bélgica', 'BE');
INSERT INTO countries VALUES (084, 'Belice', 'BZ');
INSERT INTO countries VALUES (204, 'Benin', 'BJ');
INSERT INTO countries VALUES (060, 'Bermudas', 'BM');
INSERT INTO countries VALUES (064, 'Bhután', 'BT');
INSERT INTO countries VALUES (068, 'Bolivia', 'BO');
INSERT INTO countries VALUES (070, 'Bosnia y Herzegovina', 'BA');
INSERT INTO countries VALUES (072, 'Botsuana', 'BW');
INSERT INTO countries VALUES (074, 'Isla Bouvet', 'BV');
INSERT INTO countries VALUES (076, 'Brasil', 'BR');
INSERT INTO countries VALUES (096, 'Brunéi', 'BN');
INSERT INTO countries VALUES (100, 'Bulgaria', 'BG');
INSERT INTO countries VALUES (854, 'Burkina Faso', 'BF');
INSERT INTO countries VALUES (108, 'Burundi', 'BI');
INSERT INTO countries VALUES (132, 'Cabo Verde', 'CV');
INSERT INTO countries VALUES (136, 'Islas Caimán', 'KY');
INSERT INTO countries VALUES (116, 'Camboya', 'KH');
INSERT INTO countries VALUES (120, 'Camerún', 'CM');
INSERT INTO countries VALUES (124, 'Canadá', 'CA');
INSERT INTO countries VALUES (140, 'República Centroafricana', 'CF');
INSERT INTO countries VALUES (148, 'Chad', 'TD');
INSERT INTO countries VALUES (203, 'Chequia', 'CZ');
INSERT INTO countries VALUES (152, 'Chile', 'CL');
INSERT INTO countries VALUES (156, 'China', 'CN');
INSERT INTO countries VALUES (196, 'Chipre', 'CY');
INSERT INTO countries VALUES (162, 'Isla Christmas', 'CX');
INSERT INTO countries VALUES (275, 'Cisjordania', 'PS');
INSERT INTO countries VALUES (336, 'Ciudad del Vaticano', 'VA');
INSERT INTO countries VALUES (166, 'Islas Cocos', 'CC');
INSERT INTO countries VALUES (170, 'Colombia', 'CO');
INSERT INTO countries VALUES (174, 'Comoras', 'KM');
INSERT INTO countries VALUES (180, 'República Democrática del Congo', 'CD');
INSERT INTO countries VALUES (178, 'Congo', 'CG');
INSERT INTO countries VALUES (184, 'Islas Cook', 'CK');
INSERT INTO countries VALUES (408, 'Corea del Norte', 'KP');
INSERT INTO countries VALUES (410, 'Corea del Sur', 'KR');
INSERT INTO countries VALUES (384, 'Costa de Marfil', 'CI');
INSERT INTO countries VALUES (188, 'Costa Rica', 'CR');
INSERT INTO countries VALUES (191, 'Croacia', 'HR');
INSERT INTO countries VALUES (192, 'Cuba', 'CU');
INSERT INTO countries VALUES (208, 'Dinamarca', 'DK');
INSERT INTO countries VALUES (212, 'Dominica', 'DM');
INSERT INTO countries VALUES (214, 'República Dominicana', 'DO');
INSERT INTO countries VALUES (218, 'Ecuador', 'EC');
INSERT INTO countries VALUES (818, 'Egipto', 'EG');
INSERT INTO countries VALUES (222, 'El Salvador', 'SV');
INSERT INTO countries VALUES (784, 'Emiratos Árabes Unidos', 'AE');
INSERT INTO countries VALUES (232, 'Eritrea', 'ER');
INSERT INTO countries VALUES (703, 'Eslovaquia', 'SK');
INSERT INTO countries VALUES (705, 'Eslovenia', 'SI');
INSERT INTO countries VALUES (724, 'España', 'ES');
INSERT INTO countries VALUES (581, 'Islas Ultramarinas de Estados Unidos', 'UM');
INSERT INTO countries VALUES (840, 'Estados Unidos', 'US');
INSERT INTO countries VALUES (233, 'Estonia', 'EE');
INSERT INTO countries VALUES (231, 'Etiopía', 'ET');
INSERT INTO countries VALUES (234, 'Islas Feroe', 'FO');
INSERT INTO countries VALUES (608, 'Filipinas', 'PH');
INSERT INTO countries VALUES (246, 'Finlandia', 'FI');
INSERT INTO countries VALUES (242, 'Fiyi', 'FJ');
INSERT INTO countries VALUES (250, 'Francia', 'FR');
INSERT INTO countries VALUES (266, 'Gabón', 'GA');
INSERT INTO countries VALUES (270, 'Gambia', 'GM');
INSERT INTO countries VALUES (268, 'Georgia', 'GE');
INSERT INTO countries VALUES (239, 'Georgia del Sur', 'GS');
INSERT INTO countries VALUES (288, 'Ghana', 'GH');
INSERT INTO countries VALUES (292, 'Gibraltar', 'GI');
INSERT INTO countries VALUES (308, 'Granada', 'GD');
INSERT INTO countries VALUES (300, 'Grecia', 'GR');
INSERT INTO countries VALUES (304, 'Groenlandia', 'GL');
INSERT INTO countries VALUES (312, 'Guadalupe', 'GP');
INSERT INTO countries VALUES (316, 'Guam', 'GU');
INSERT INTO countries VALUES (320, 'Guatemala', 'GT');
INSERT INTO countries VALUES (254, 'Guayana Francesa', 'GF');
INSERT INTO countries VALUES (324, 'Guinea', 'GN');
INSERT INTO countries VALUES (226, 'Guinea Ecuatorial', 'GQ');
INSERT INTO countries VALUES (624, 'Guinea-Bissau', 'GW');
INSERT INTO countries VALUES (328, 'Guyana', 'GY');
INSERT INTO countries VALUES (332, 'Haití', 'HT');
INSERT INTO countries VALUES (334, 'Islas Heard y McDonald', 'HM');
INSERT INTO countries VALUES (340, 'Honduras', 'HN');
INSERT INTO countries VALUES (344, 'Hong Kong', 'HK');
INSERT INTO countries VALUES (348, 'Hungría', 'HU');
INSERT INTO countries VALUES (356, 'India', 'IN');
INSERT INTO countries VALUES (360, 'Indonesia', 'ID');
INSERT INTO countries VALUES (364, 'Irán', 'IR');
INSERT INTO countries VALUES (368, 'Iraq', 'IQ');
INSERT INTO countries VALUES (372, 'Irlanda', 'IE');
INSERT INTO countries VALUES (352, 'Islandia', 'IS');
INSERT INTO countries VALUES (376, 'Israel', 'IL');
INSERT INTO countries VALUES (380, 'Italia', 'IT');
INSERT INTO countries VALUES (388, 'Jamaica', 'JM');
INSERT INTO countries VALUES (392, 'Japón', 'JP');
INSERT INTO countries VALUES (400, 'Jordania', 'JO');
INSERT INTO countries VALUES (398, 'Kazajstán', 'KZ');
INSERT INTO countries VALUES (404, 'Kenia', 'KE');
INSERT INTO countries VALUES (417, 'Kirguistán', 'KG');
INSERT INTO countries VALUES (296, 'Kiribati', 'KI');
INSERT INTO countries VALUES (414, 'Kuwait', 'KW');
INSERT INTO countries VALUES (418, 'Laos', 'LA');
INSERT INTO countries VALUES (426, 'Lesotho', 'LS');
INSERT INTO countries VALUES (428, 'Letonia', 'LV');
INSERT INTO countries VALUES (422, 'Líbano', 'LB');
INSERT INTO countries VALUES (430, 'Liberia', 'LR');
INSERT INTO countries VALUES (434, 'Libia', 'LY');
INSERT INTO countries VALUES (438, 'Liechtenstein', 'LI');
INSERT INTO countries VALUES (440, 'Lituania', 'LT');
INSERT INTO countries VALUES (442, 'Luxemburgo', 'LU');
INSERT INTO countries VALUES (446, 'Macao', 'MO');
INSERT INTO countries VALUES (807, 'ARY Macedonia', 'MK');
INSERT INTO countries VALUES (450, 'Madagascar', 'MG');
INSERT INTO countries VALUES (458, 'Malasia', 'MY');
INSERT INTO countries VALUES (454, 'Malawi', 'MW');
INSERT INTO countries VALUES (462, 'Maldivas', 'MV');
INSERT INTO countries VALUES (466, 'Malí', 'ML');
INSERT INTO countries VALUES (470, 'Malta', 'MT');
INSERT INTO countries VALUES (238, 'Islas Malvinas', 'FK');
INSERT INTO countries VALUES (580, 'Islas Marianas del Norte', 'MP');
INSERT INTO countries VALUES (504, 'Marruecos', 'MA');
INSERT INTO countries VALUES (584, 'Islas Marshall', 'MH');
INSERT INTO countries VALUES (474, 'Martinica', 'MQ');
INSERT INTO countries VALUES (480, 'Mauricio', 'MU');
INSERT INTO countries VALUES (478, 'Mauritania', 'MR');
INSERT INTO countries VALUES (175, 'Mayotte', 'YT');
INSERT INTO countries VALUES (484, 'México', 'MX');
INSERT INTO countries VALUES (583, 'Micronesia', 'FM');
INSERT INTO countries VALUES (498, 'Moldova', 'MD');
INSERT INTO countries VALUES (492, 'Mónaco', 'MC');
INSERT INTO countries VALUES (496, 'Mongolia', 'MN');
INSERT INTO countries VALUES (500, 'Montserrat', 'MS');
INSERT INTO countries VALUES (508, 'Mozambique', 'MZ');
INSERT INTO countries VALUES (104, 'Myanmar', 'MM');
INSERT INTO countries VALUES (516, 'Namibia', 'NA');
INSERT INTO countries VALUES (520, 'Nauru', 'NR');
INSERT INTO countries VALUES (524, 'Nepal', 'NP');
INSERT INTO countries VALUES (558, 'Nicaragua', 'NI');
INSERT INTO countries VALUES (562, 'Níger', 'NE');
INSERT INTO countries VALUES (566, 'Nigeria', 'NG');
INSERT INTO countries VALUES (570, 'Niue', 'NU');
INSERT INTO countries VALUES (574, 'Isla Norfolk', 'NF');
INSERT INTO countries VALUES (578, 'Noruega', 'NO');
INSERT INTO countries VALUES (540, 'Nueva Caledonia', 'NC');
INSERT INTO countries VALUES (554, 'Nueva Zelanda', 'NZ');
INSERT INTO countries VALUES (512, 'Omán', 'OM');
INSERT INTO countries VALUES (528, 'Países Bajos', 'NL');
INSERT INTO countries VALUES (586, 'Pakistán', 'PK');
INSERT INTO countries VALUES (585, 'Palaos', 'PW');
INSERT INTO countries VALUES (591, 'Panamá', 'PA');
INSERT INTO countries VALUES (598, 'Papúa Nueva Guinea', 'PG');
INSERT INTO countries VALUES (600, 'Paraguay', 'PY');
INSERT INTO countries VALUES (604, 'Perú', 'PE');
INSERT INTO countries VALUES (612, 'Islas Pitcairn', 'PN');
INSERT INTO countries VALUES (258, 'Polinesia Francesa', 'PF');
INSERT INTO countries VALUES (616, 'Polonia', 'PL');
INSERT INTO countries VALUES (620, 'Portugal', 'PT');
INSERT INTO countries VALUES (630, 'Puerto Rico', 'PR');
INSERT INTO countries VALUES (634, 'Qatar', 'QA');
INSERT INTO countries VALUES (826, 'Reino Unido', 'GB');
INSERT INTO countries VALUES (638, 'Reunión', 'RE');
INSERT INTO countries VALUES (646, 'Ruanda', 'RW');
INSERT INTO countries VALUES (642, 'Rumanía', 'RO');
INSERT INTO countries VALUES (643, 'Rusia', 'RU');
INSERT INTO countries VALUES (732, 'Sáhara Occidental', 'EH');
INSERT INTO countries VALUES (090, 'Islas Salomón', 'SB');
INSERT INTO countries VALUES (882, 'Samoa', 'WS');
INSERT INTO countries VALUES (016, 'Samoa Americana', 'AS');
INSERT INTO countries VALUES (659, 'San Cristóbal y Nieves', 'KN');
INSERT INTO countries VALUES (674, 'San Marino', 'SM');
INSERT INTO countries VALUES (666, 'San Pedro y Miquelón', 'PM');
INSERT INTO countries VALUES (670, 'San Vicente y las Granadinas', 'VC');
INSERT INTO countries VALUES (654, 'Santa Helena', 'SH');
INSERT INTO countries VALUES (662, 'Santa Lucía', 'LC');
INSERT INTO countries VALUES (678, 'Santo Tomé y Príncipe', 'ST');
INSERT INTO countries VALUES (686, 'Senegal', 'SN');
INSERT INTO countries VALUES (891, 'Serbia y Montenegro', 'CS');
INSERT INTO countries VALUES (690, 'Seychelles', 'SC');
INSERT INTO countries VALUES (694, 'Sierra Leona', 'SL');
INSERT INTO countries VALUES (702, 'Singapur', 'SG');
INSERT INTO countries VALUES (760, 'Siria', 'SY');
INSERT INTO countries VALUES (706, 'Somalia', 'SO');
INSERT INTO countries VALUES (144, 'Sri Lanka', 'LK');
INSERT INTO countries VALUES (748, 'Suazilandia', 'SZ');
INSERT INTO countries VALUES (710, 'Sudáfrica', 'ZA');
INSERT INTO countries VALUES (736, 'Sudán', 'SD');
INSERT INTO countries VALUES (752, 'Suecia', 'SE');
INSERT INTO countries VALUES (756, 'Suiza', 'CH');
INSERT INTO countries VALUES (740, 'Surinam', 'SR');
INSERT INTO countries VALUES (744, 'Svalbard', 'SJ');
INSERT INTO countries VALUES (764, 'Tailandia', 'TH');
INSERT INTO countries VALUES (158, 'Taiwán', 'TW');
INSERT INTO countries VALUES (834, 'Tanzania', 'TZ');
INSERT INTO countries VALUES (762, 'Tayikistán', 'TJ');
INSERT INTO countries VALUES (086, 'Territorio Británico del Océano Índico', 'IO');
INSERT INTO countries VALUES (260, 'Territorios Australes Franceses', 'TF');
INSERT INTO countries VALUES (626, 'Timor Oriental', 'TL');
INSERT INTO countries VALUES (768, 'Togo', 'TG');
INSERT INTO countries VALUES (772, 'Tokelau', 'TK');
INSERT INTO countries VALUES (776, 'Tonga', 'TO');
INSERT INTO countries VALUES (780, 'Trinidad y Tobago', 'TT');
INSERT INTO countries VALUES (788, 'Túnez', 'TN');
INSERT INTO countries VALUES (796, 'Islas Turcas y Caicos', 'TC');
INSERT INTO countries VALUES (795, 'Turkmenistán', 'TM');
INSERT INTO countries VALUES (792, 'Turquía', 'TR');
INSERT INTO countries VALUES (798, 'Tuvalu', 'TV');
INSERT INTO countries VALUES (804, 'Ucrania', 'UA');
INSERT INTO countries VALUES (800, 'Uganda', 'UG');
INSERT INTO countries VALUES (858, 'Uruguay', 'UY');
INSERT INTO countries VALUES (860, 'Uzbekistán', 'UZ');
INSERT INTO countries VALUES (548, 'Vanuatu', 'VU');
INSERT INTO countries VALUES (862, 'Venezuela', 'VE');
INSERT INTO countries VALUES (704, 'Vietnam', 'VN');
INSERT INTO countries VALUES (092, 'Islas Vírgenes Británicas', 'VG');
INSERT INTO countries VALUES (850, 'Islas Vírgenes de los Estados Unidos', 'VI');
INSERT INTO countries VALUES (876, 'Islas Wallis y Futuna', 'WF');
INSERT INTO countries VALUES (887, 'Yemen', 'YE');
INSERT INTO countries VALUES (262, 'Yibuti', 'DJ');
INSERT INTO countries VALUES (894, 'Zambia', 'ZM');
INSERT INTO countries VALUES (716, 'Zimbabue', 'ZW');
