INSERT INTO languages (name, code) VALUES ('Afar', 'aa');
INSERT INTO languages (name, code) VALUES ('Abkhazian', 'ab');
INSERT INTO languages (name, code) VALUES ('Avestan', 'ae');
INSERT INTO languages (name, code) VALUES ('Afrikaans', 'af');
INSERT INTO languages (name, code) VALUES ('Akan', 'ak');
INSERT INTO languages (name, code) VALUES ('Amharic', 'am');
INSERT INTO languages (name, code) VALUES ('Aragonese', 'an');
INSERT INTO languages (name, code) VALUES ('Angika', 'anp');
INSERT INTO languages (name, code) VALUES ('Arabic', 'ar');
INSERT INTO languages (name, code) VALUES ('Assamese', 'as');
INSERT INTO languages (name, code) VALUES ('Avaric', 'av');
INSERT INTO languages (name, code) VALUES ('Aymara', 'ay');
INSERT INTO languages (name, code) VALUES ('Azerbaijani', 'az');
INSERT INTO languages (name, code) VALUES ('Bashkir', 'ba');
INSERT INTO languages (name, code) VALUES ('Belarusian', 'be');
INSERT INTO languages (name, code) VALUES ('Bulgarian', 'bg');
INSERT INTO languages (name, code) VALUES ('Bihari', 'bh');
INSERT INTO languages (name, code) VALUES ('Bislama', 'bi');
INSERT INTO languages (name, code) VALUES ('Bambara', 'bm');
INSERT INTO languages (name, code) VALUES ('Bengali', 'bn');
INSERT INTO languages (name, code) VALUES ('Tibetan', 'bo');
INSERT INTO languages (name, code) VALUES ('Breton', 'br');
INSERT INTO languages (name, code) VALUES ('Bosnian', 'bs');
INSERT INTO languages (name, code) VALUES ('Catalan', 'ca');
INSERT INTO languages (name, code) VALUES ('Chechen', 'ce');
INSERT INTO languages (name, code) VALUES ('Chamorro', 'ch');
INSERT INTO languages (name, code) VALUES ('Corsican', 'co');
INSERT INTO languages (name, code) VALUES ('Cree', 'cr');
INSERT INTO languages (name, code) VALUES ('Czech', 'cs');
INSERT INTO languages (name, code) VALUES ('Church Slavic', 'cu');
INSERT INTO languages (name, code) VALUES ('Chuvash', 'cv');
INSERT INTO languages (name, code) VALUES ('Welsh', 'cy');
INSERT INTO languages (name, code) VALUES ('Danish', 'da');
INSERT INTO languages (name, code) VALUES ('German', 'de');
INSERT INTO languages (name, code) VALUES ('Divehi', 'dv');
INSERT INTO languages (name, code) VALUES ('Dzongkha', 'dz');
INSERT INTO languages (name, code) VALUES ('Ewe', 'ee');
INSERT INTO languages (name, code) VALUES ('Greek, Modern (1453-)', 'el');
INSERT INTO languages (name, code) VALUES ('English', 'en');
INSERT INTO languages (name, code) VALUES ('Esperanto', 'eo');
INSERT INTO languages (name, code) VALUES ('Spanish', 'es');
INSERT INTO languages (name, code) VALUES ('Estonian', 'et');
INSERT INTO languages (name, code) VALUES ('Basque', 'eu');
INSERT INTO languages (name, code) VALUES ('Persian', 'fa');
INSERT INTO languages (name, code) VALUES ('Fulah', 'ff');
INSERT INTO languages (name, code) VALUES ('Finnish', 'fi');
INSERT INTO languages (name, code) VALUES ('Fijian', 'fj');
INSERT INTO languages (name, code) VALUES ('Faroese', 'fo');
INSERT INTO languages (name, code) VALUES ('French', 'fr');
INSERT INTO languages (name, code) VALUES ('Northern Frisian', 'frr');
INSERT INTO languages (name, code) VALUES ('Western Frisian', 'fy');
INSERT INTO languages (name, code) VALUES ('Irish', 'ga');
INSERT INTO languages (name, code) VALUES ('Gaelic', 'gd');
INSERT INTO languages (name, code) VALUES ('Galician', 'gl');
INSERT INTO languages (name, code) VALUES ('Guarani', 'gn');
INSERT INTO languages (name, code) VALUES ('Gujarati', 'gu');
INSERT INTO languages (name, code) VALUES ('Manx', 'gv');
INSERT INTO languages (name, code) VALUES ('Hausa', 'ha');
INSERT INTO languages (name, code) VALUES ('Hebrew', 'he');
INSERT INTO languages (name, code) VALUES ('Hindi', 'hi');
INSERT INTO languages (name, code) VALUES ('Hiri Motu', 'ho');
INSERT INTO languages (name, code) VALUES ('Croatian', 'hr');
INSERT INTO languages (name, code) VALUES ('Haitian', 'ht');
INSERT INTO languages (name, code) VALUES ('Hungarian', 'hu');
INSERT INTO languages (name, code) VALUES ('Armenian', 'hy');
INSERT INTO languages (name, code) VALUES ('Herero', 'hz');
INSERT INTO languages (name, code) VALUES ('Interlingua (International Auxiliary Language', 'ia');
INSERT INTO languages (name, code) VALUES ('Indonesian', 'id');
INSERT INTO languages (name, code) VALUES ('Interlingue', 'ie');
INSERT INTO languages (name, code) VALUES ('Igbo', 'ig');
INSERT INTO languages (name, code) VALUES ('Sichuan Yi', 'ii');
INSERT INTO languages (name, code) VALUES ('Inupiaq', 'ik');
INSERT INTO languages (name, code) VALUES ('Indonesian', 'in');
INSERT INTO languages (name, code) VALUES ('Ido', 'io');
INSERT INTO languages (name, code) VALUES ('Icelandic', 'is');
INSERT INTO languages (name, code) VALUES ('Italian', 'it');
INSERT INTO languages (name, code) VALUES ('Inuktitut', 'iu');
INSERT INTO languages (name, code) VALUES ('Hebrew', 'iw');
INSERT INTO languages (name, code) VALUES ('Japanese', 'ja');
INSERT INTO languages (name, code) VALUES ('Yiddish', 'ji');
INSERT INTO languages (name, code) VALUES ('Javanese', 'jv');
INSERT INTO languages (name, code) VALUES ('Javanese', 'jw');
INSERT INTO languages (name, code) VALUES ('Georgian', 'ka');
INSERT INTO languages (name, code) VALUES ('Kongo', 'kg');
INSERT INTO languages (name, code) VALUES ('Kikuyu', 'ki');
INSERT INTO languages (name, code) VALUES ('Kuanyama', 'kj');
INSERT INTO languages (name, code) VALUES ('Kazakh', 'kk');
INSERT INTO languages (name, code) VALUES ('Kalaallisut', 'kl');
INSERT INTO languages (name, code) VALUES ('Central Khmer', 'km');
INSERT INTO languages (name, code) VALUES ('Kannada', 'kn');
INSERT INTO languages (name, code) VALUES ('Korean', 'ko');
INSERT INTO languages (name, code) VALUES ('Kanuri', 'kr');
INSERT INTO languages (name, code) VALUES ('Kashmiri', 'ks');
INSERT INTO languages (name, code) VALUES ('Kurdish', 'ku');
INSERT INTO languages (name, code) VALUES ('Komi', 'kv');
INSERT INTO languages (name, code) VALUES ('Cornish', 'kw');
INSERT INTO languages (name, code) VALUES ('Kyrgyz', 'ky');
INSERT INTO languages (name, code) VALUES ('Latin', 'la');
INSERT INTO languages (name, code) VALUES ('Luxembourgish', 'lb');
INSERT INTO languages (name, code) VALUES ('Ganda', 'lg');
INSERT INTO languages (name, code) VALUES ('Limburgan', 'li');
INSERT INTO languages (name, code) VALUES ('Lingala', 'ln');
INSERT INTO languages (name, code) VALUES ('Lao', 'lo');
INSERT INTO languages (name, code) VALUES ('Lithuanian', 'lt');
INSERT INTO languages (name, code) VALUES ('Luba-Katanga', 'lu');
INSERT INTO languages (name, code) VALUES ('Latvian', 'lv');
INSERT INTO languages (name, code) VALUES ('Malagasy', 'mg');
INSERT INTO languages (name, code) VALUES ('Marshallese', 'mh');
INSERT INTO languages (name, code) VALUES ('Maori', 'mi');
INSERT INTO languages (name, code) VALUES ('Macedonian', 'mk');
INSERT INTO languages (name, code) VALUES ('Malayalam', 'ml');
INSERT INTO languages (name, code) VALUES ('Mongolian', 'mn');
INSERT INTO languages (name, code) VALUES ('Moldavian', 'mo');
INSERT INTO languages (name, code) VALUES ('Marathi', 'mr');
INSERT INTO languages (name, code) VALUES ('Malay', 'ms');
INSERT INTO languages (name, code) VALUES ('Maltese', 'mt');
INSERT INTO languages (name, code) VALUES ('Burmese', 'my');
INSERT INTO languages (name, code) VALUES ('Nauru', 'na');
INSERT INTO languages (name, code) VALUES ('Norwegian Bokm&#xE5;l', 'nb');
INSERT INTO languages (name, code) VALUES ('Ndebele, North', 'nd');
INSERT INTO languages (name, code) VALUES ('Nepali', 'ne');
INSERT INTO languages (name, code) VALUES ('Ndonga', 'ng');
INSERT INTO languages (name, code) VALUES ('Dutch', 'nl');
INSERT INTO languages (name, code) VALUES ('Norwegian Nynorsk', 'nn');
INSERT INTO languages (name, code) VALUES ('Norwegian', 'no');
INSERT INTO languages (name, code) VALUES ('Ndebele, South', 'nr');
INSERT INTO languages (name, code) VALUES ('Navajo', 'nv');
INSERT INTO languages (name, code) VALUES ('Chichewa', 'ny');
INSERT INTO languages (name, code) VALUES ('Occitan (post 1500)', 'oc');
INSERT INTO languages (name, code) VALUES ('Ojibwa', 'oj');
INSERT INTO languages (name, code) VALUES ('Oromo', 'om');
INSERT INTO languages (name, code) VALUES ('Oriya', 'or');
INSERT INTO languages (name, code) VALUES ('Ossetian', 'os');
INSERT INTO languages (name, code) VALUES ('Panjabi', 'pa');
INSERT INTO languages (name, code) VALUES ('Pali', 'pi');
INSERT INTO languages (name, code) VALUES ('Polish', 'pl');
INSERT INTO languages (name, code) VALUES ('Pushto', 'ps');
INSERT INTO languages (name, code) VALUES ('Portuguese', 'pt');
INSERT INTO languages (name, code) VALUES ('Quechua', 'qu');
INSERT INTO languages (name, code) VALUES ('Romansh', 'rm');
INSERT INTO languages (name, code) VALUES ('Rundi', 'rn');
INSERT INTO languages (name, code) VALUES ('Romanian', 'ro');
INSERT INTO languages (name, code) VALUES ('Russian', 'ru');
INSERT INTO languages (name, code) VALUES ('Kinyarwanda', 'rw');
INSERT INTO languages (name, code) VALUES ('Sanskrit', 'sa');
INSERT INTO languages (name, code) VALUES ('Sardinian', 'sc');
INSERT INTO languages (name, code) VALUES ('Sindhi', 'sd');
INSERT INTO languages (name, code) VALUES ('Northern Sami', 'se');
INSERT INTO languages (name, code) VALUES ('Sango', 'sg');
INSERT INTO languages (name, code) VALUES ('Serbo-Croatian', 'sh');
INSERT INTO languages (name, code) VALUES ('Sinhala', 'si');
INSERT INTO languages (name, code) VALUES ('Slovak', 'sk');
INSERT INTO languages (name, code) VALUES ('Slovenian', 'sl');
INSERT INTO languages (name, code) VALUES ('Samoan', 'sm');
INSERT INTO languages (name, code) VALUES ('Shona', 'sn');
INSERT INTO languages (name, code) VALUES ('Somali', 'so');
INSERT INTO languages (name, code) VALUES ('Albanian', 'sq');
INSERT INTO languages (name, code) VALUES ('Serbian', 'sr');
INSERT INTO languages (name, code) VALUES ('Swati', 'ss');
INSERT INTO languages (name, code) VALUES ('Sotho, Southern', 'st');
INSERT INTO languages (name, code) VALUES ('Sundanese', 'su');
INSERT INTO languages (name, code) VALUES ('Swedish', 'sv');
INSERT INTO languages (name, code) VALUES ('Swahili', 'sw');
INSERT INTO languages (name, code) VALUES ('Tamil', 'ta');
INSERT INTO languages (name, code) VALUES ('Telugu', 'te');
INSERT INTO languages (name, code) VALUES ('Tajik', 'tg');
INSERT INTO languages (name, code) VALUES ('Thai', 'th');
INSERT INTO languages (name, code) VALUES ('Tigrinya', 'ti');
INSERT INTO languages (name, code) VALUES ('Turkmen', 'tk');
INSERT INTO languages (name, code) VALUES ('Tagalog', 'tl');
INSERT INTO languages (name, code) VALUES ('Tswana', 'tn');
INSERT INTO languages (name, code) VALUES ('Tonga (Tonga Islands)', 'to');
INSERT INTO languages (name, code) VALUES ('Turkish', 'tr');
INSERT INTO languages (name, code) VALUES ('Tsonga', 'ts');
INSERT INTO languages (name, code) VALUES ('Tatar', 'tt');
INSERT INTO languages (name, code) VALUES ('Twi', 'tw');
INSERT INTO languages (name, code) VALUES ('Tahitian', 'ty');
INSERT INTO languages (name, code) VALUES ('Uighur', 'ug');
INSERT INTO languages (name, code) VALUES ('Ukrainian', 'uk');
INSERT INTO languages (name, code) VALUES ('Urdu', 'ur');
INSERT INTO languages (name, code) VALUES ('Uzbek', 'uz');
INSERT INTO languages (name, code) VALUES ('Venda', 've');
INSERT INTO languages (name, code) VALUES ('Vietnamese', 'vi');
INSERT INTO languages (name, code) VALUES ('Volap&#xFC;k', 'vo');
INSERT INTO languages (name, code) VALUES ('Walloon', 'wa');
INSERT INTO languages (name, code) VALUES ('Wolof', 'wo');
INSERT INTO languages (name, code) VALUES ('Xhosa', 'xh');
INSERT INTO languages (name, code) VALUES ('Yiddish', 'yi');
INSERT INTO languages (name, code) VALUES ('Yoruba', 'yo');
INSERT INTO languages (name, code) VALUES ('Zhuang', 'za');
INSERT INTO languages (name, code) VALUES ('Chinese', 'zh');
INSERT INTO languages (name, code) VALUES ('Zulu', 'zu');
INSERT INTO languages (name, code) VALUES ('Achinese', 'ace');
INSERT INTO languages (name, code) VALUES ('Acoli', 'ach');
INSERT INTO languages (name, code) VALUES ('Adangme', 'ada');
INSERT INTO languages (name, code) VALUES ('Adyghe', 'ady');
INSERT INTO languages (name, code) VALUES ('Afro-Asiatic (Other)', 'afa');
INSERT INTO languages (name, code) VALUES ('Afrihili', 'afh');
INSERT INTO languages (name, code) VALUES ('Ainu', 'ain');
INSERT INTO languages (name, code) VALUES ('Akkadian', 'akk');
INSERT INTO languages (name, code) VALUES ('Aleut', 'ale');
INSERT INTO languages (name, code) VALUES ('Algonquian languages', 'alg');
INSERT INTO languages (name, code) VALUES ('Southern Altai', 'alt');
INSERT INTO languages (name, code) VALUES ('English, Old (ca. 450-1100)', 'ang');
INSERT INTO languages (name, code) VALUES ('Apache languages', 'apa');
INSERT INTO languages (name, code) VALUES ('Aramaic', 'arc');
INSERT INTO languages (name, code) VALUES ('Mapudungun', 'arn');
INSERT INTO languages (name, code) VALUES ('Arapaho', 'arp');
INSERT INTO languages (name, code) VALUES ('Artificial (Other)', 'art');
INSERT INTO languages (name, code) VALUES ('Arawak', 'arw');
INSERT INTO languages (name, code) VALUES ('Asturian', 'ast');
INSERT INTO languages (name, code) VALUES ('Athapascan languages', 'ath');
INSERT INTO languages (name, code) VALUES ('Australian languages', 'aus');
INSERT INTO languages (name, code) VALUES ('Awadhi', 'awa');
INSERT INTO languages (name, code) VALUES ('Banda languages', 'bad');
INSERT INTO languages (name, code) VALUES ('Bamileke languages', 'bai');
INSERT INTO languages (name, code) VALUES ('Baluchi', 'bal');
INSERT INTO languages (name, code) VALUES ('Balinese', 'ban');
INSERT INTO languages (name, code) VALUES ('Basa', 'bas');
INSERT INTO languages (name, code) VALUES ('Baltic (Other)', 'bat');
INSERT INTO languages (name, code) VALUES ('Beja', 'bej');
INSERT INTO languages (name, code) VALUES ('Bemba', 'bem');
INSERT INTO languages (name, code) VALUES ('Berber (Other)', 'ber');
INSERT INTO languages (name, code) VALUES ('Bhojpuri', 'bho');
INSERT INTO languages (name, code) VALUES ('Bikol', 'bik');
INSERT INTO languages (name, code) VALUES ('Bini', 'bin');
INSERT INTO languages (name, code) VALUES ('Siksika', 'bla');
INSERT INTO languages (name, code) VALUES ('Bantu (Other)', 'bnt');
INSERT INTO languages (name, code) VALUES ('Braj', 'bra');
INSERT INTO languages (name, code) VALUES ('Batak languages', 'btk');
INSERT INTO languages (name, code) VALUES ('Buriat', 'bua');
INSERT INTO languages (name, code) VALUES ('Buginese', 'bug');
INSERT INTO languages (name, code) VALUES ('Blin', 'byn');
INSERT INTO languages (name, code) VALUES ('Caddo', 'cad');
INSERT INTO languages (name, code) VALUES ('Central American Indian (Other)', 'cai');
INSERT INTO languages (name, code) VALUES ('Galibi Carib', 'car');
INSERT INTO languages (name, code) VALUES ('Caucasian (Other)', 'cau');
INSERT INTO languages (name, code) VALUES ('Cebuano', 'ceb');
INSERT INTO languages (name, code) VALUES ('Celtic (Other)', 'cel');
INSERT INTO languages (name, code) VALUES ('Chibcha', 'chb');
INSERT INTO languages (name, code) VALUES ('Chagatai', 'chg');
INSERT INTO languages (name, code) VALUES ('Chuukese', 'chk');
INSERT INTO languages (name, code) VALUES ('Mari', 'chm');
INSERT INTO languages (name, code) VALUES ('Chinook jargon', 'chn');
INSERT INTO languages (name, code) VALUES ('Choctaw', 'cho');
INSERT INTO languages (name, code) VALUES ('Chipewyan', 'chp');
INSERT INTO languages (name, code) VALUES ('Cherokee', 'chr');
INSERT INTO languages (name, code) VALUES ('Cheyenne', 'chy');
INSERT INTO languages (name, code) VALUES ('Chamic languages', 'cmc');
INSERT INTO languages (name, code) VALUES ('Coptic', 'cop');
INSERT INTO languages (name, code) VALUES ('Creoles and pidgins, English-based (Other)', 'cpe');
INSERT INTO languages (name, code) VALUES ('Creoles and pidgins, French-based (Other)', 'cpf');
INSERT INTO languages (name, code) VALUES ('Creoles and pidgins, Portuguese-based (Other)', 'cpp');
INSERT INTO languages (name, code) VALUES ('Crimean Tatar', 'crh');
INSERT INTO languages (name, code) VALUES ('Creoles and pidgins (Other)', 'crp');
INSERT INTO languages (name, code) VALUES ('Kashubian', 'csb');
INSERT INTO languages (name, code) VALUES ('Cushitic (Other)', 'cus');
INSERT INTO languages (name, code) VALUES ('Dakota', 'dak');
INSERT INTO languages (name, code) VALUES ('Dargwa', 'dar');
INSERT INTO languages (name, code) VALUES ('Land Dayak languages', 'day');
INSERT INTO languages (name, code) VALUES ('Delaware', 'del');
INSERT INTO languages (name, code) VALUES ('Slave (Athapascan)', 'den');
INSERT INTO languages (name, code) VALUES ('Dogrib', 'dgr');
INSERT INTO languages (name, code) VALUES ('Dinka', 'din');
INSERT INTO languages (name, code) VALUES ('Dogri', 'doi');
INSERT INTO languages (name, code) VALUES ('Dravidian (Other)', 'dra');
INSERT INTO languages (name, code) VALUES ('Lower Sorbian', 'dsb');
INSERT INTO languages (name, code) VALUES ('Duala', 'dua');
INSERT INTO languages (name, code) VALUES ('Dutch, Middle (ca. 1050-1350)', 'dum');
INSERT INTO languages (name, code) VALUES ('Dyula', 'dyu');
INSERT INTO languages (name, code) VALUES ('Efik', 'efi');
INSERT INTO languages (name, code) VALUES ('Egyptian (Ancient)', 'egy');
INSERT INTO languages (name, code) VALUES ('Ekajuk', 'eka');
INSERT INTO languages (name, code) VALUES ('Elamite', 'elx');
INSERT INTO languages (name, code) VALUES ('English, Middle (1100-1500)', 'enm');
INSERT INTO languages (name, code) VALUES ('Ewondo', 'ewo');
INSERT INTO languages (name, code) VALUES ('Fang', 'fan');
INSERT INTO languages (name, code) VALUES ('Fanti', 'fat');
INSERT INTO languages (name, code) VALUES ('Filipino', 'fil');
INSERT INTO languages (name, code) VALUES ('Finno-Ugrian (Other)', 'fiu');
INSERT INTO languages (name, code) VALUES ('Fon', 'fon');
INSERT INTO languages (name, code) VALUES ('French, Middle (ca. 1400-1600)', 'frm');
INSERT INTO languages (name, code) VALUES ('French, Old (842-ca. 1400)', 'fro');
INSERT INTO languages (name, code) VALUES ('Eastern Frisian', 'frs');
INSERT INTO languages (name, code) VALUES ('Friulian', 'fur');
INSERT INTO languages (name, code) VALUES ('Ga', 'gaa');
INSERT INTO languages (name, code) VALUES ('Gayo', 'gay');
INSERT INTO languages (name, code) VALUES ('Gbaya', 'gba');
INSERT INTO languages (name, code) VALUES ('Germanic (Other)', 'gem');
INSERT INTO languages (name, code) VALUES ('Geez', 'gez');
INSERT INTO languages (name, code) VALUES ('Gilbertese', 'gil');
INSERT INTO languages (name, code) VALUES ('German, Middle High (ca. 1050-1500)', 'gmh');
INSERT INTO languages (name, code) VALUES ('German, Old High (ca. 750-1050)', 'goh');
INSERT INTO languages (name, code) VALUES ('Gondi', 'gon');
INSERT INTO languages (name, code) VALUES ('Gorontalo', 'gor');
INSERT INTO languages (name, code) VALUES ('Gothic', 'got');
INSERT INTO languages (name, code) VALUES ('Grebo', 'grb');
INSERT INTO languages (name, code) VALUES ('Greek, Ancient (to 1453)', 'grc');
INSERT INTO languages (name, code) VALUES ('Swiss German', 'gsw');
INSERT INTO languages (name, code) VALUES ('Gwich&#xB4;in', 'gwi');
INSERT INTO languages (name, code) VALUES ('Haida', 'hai');
INSERT INTO languages (name, code) VALUES ('Hawaiian', 'haw');
INSERT INTO languages (name, code) VALUES ('Hiligaynon', 'hil');
INSERT INTO languages (name, code) VALUES ('Himachali', 'him');
INSERT INTO languages (name, code) VALUES ('Hittite', 'hit');
INSERT INTO languages (name, code) VALUES ('Hmong', 'hmn');
INSERT INTO languages (name, code) VALUES ('Upper Sorbian', 'hsb');
INSERT INTO languages (name, code) VALUES ('Hupa', 'hup');
INSERT INTO languages (name, code) VALUES ('Iban', 'iba');
INSERT INTO languages (name, code) VALUES ('Ijo languages', 'ijo');
INSERT INTO languages (name, code) VALUES ('Iloko', 'ilo');
INSERT INTO languages (name, code) VALUES ('Indic (Other)', 'inc');
INSERT INTO languages (name, code) VALUES ('Indo-European (Other)', 'ine');
INSERT INTO languages (name, code) VALUES ('Ingush', 'inh');
INSERT INTO languages (name, code) VALUES ('Iranian (Other)', 'ira');
INSERT INTO languages (name, code) VALUES ('Iroquoian languages', 'iro');
INSERT INTO languages (name, code) VALUES ('Lojban', 'jbo');
INSERT INTO languages (name, code) VALUES ('Judeo-Persian', 'jpr');
INSERT INTO languages (name, code) VALUES ('Judeo-Arabic', 'jrb');
INSERT INTO languages (name, code) VALUES ('Kara-Kalpak', 'kaa');
INSERT INTO languages (name, code) VALUES ('Kabyle', 'kab');
INSERT INTO languages (name, code) VALUES ('Kachin', 'kac');
INSERT INTO languages (name, code) VALUES ('Kamba', 'kam');
INSERT INTO languages (name, code) VALUES ('Karen languages', 'kar');
INSERT INTO languages (name, code) VALUES ('Kawi', 'kaw');
INSERT INTO languages (name, code) VALUES ('Kabardian', 'kbd');
INSERT INTO languages (name, code) VALUES ('Khasi', 'kha');
INSERT INTO languages (name, code) VALUES ('Khoisan (Other)', 'khi');
INSERT INTO languages (name, code) VALUES ('Khotanese', 'kho');
INSERT INTO languages (name, code) VALUES ('Kimbundu', 'kmb');
INSERT INTO languages (name, code) VALUES ('Konkani', 'kok');
INSERT INTO languages (name, code) VALUES ('Kosraean', 'kos');
INSERT INTO languages (name, code) VALUES ('Kpelle', 'kpe');
INSERT INTO languages (name, code) VALUES ('Karachay-Balkar', 'krc');
INSERT INTO languages (name, code) VALUES ('Karelian', 'krl');
INSERT INTO languages (name, code) VALUES ('Kru languages', 'kro');
INSERT INTO languages (name, code) VALUES ('Kurukh', 'kru');
INSERT INTO languages (name, code) VALUES ('Kumyk', 'kum');
INSERT INTO languages (name, code) VALUES ('Kutenai', 'kut');
INSERT INTO languages (name, code) VALUES ('Ladino', 'lad');
INSERT INTO languages (name, code) VALUES ('Lahnda', 'lah');
INSERT INTO languages (name, code) VALUES ('Lamba', 'lam');
INSERT INTO languages (name, code) VALUES ('Lezghian', 'lez');
INSERT INTO languages (name, code) VALUES ('Mongo', 'lol');
INSERT INTO languages (name, code) VALUES ('Lozi', 'loz');
INSERT INTO languages (name, code) VALUES ('Luba-Lulua', 'lua');
INSERT INTO languages (name, code) VALUES ('Luiseno', 'lui');
INSERT INTO languages (name, code) VALUES ('Lunda', 'lun');
INSERT INTO languages (name, code) VALUES ('Luo (Kenya and Tanzania)', 'luo');
INSERT INTO languages (name, code) VALUES ('Lushai', 'lus');
INSERT INTO languages (name, code) VALUES ('Madurese', 'mad');
INSERT INTO languages (name, code) VALUES ('Magahi', 'mag');
INSERT INTO languages (name, code) VALUES ('Maithili', 'mai');
INSERT INTO languages (name, code) VALUES ('Makasar', 'mak');
INSERT INTO languages (name, code) VALUES ('Mandingo', 'man');
INSERT INTO languages (name, code) VALUES ('Austronesian (Other)', 'map');
INSERT INTO languages (name, code) VALUES ('Masai', 'mas');
INSERT INTO languages (name, code) VALUES ('Moksha', 'mdf');
INSERT INTO languages (name, code) VALUES ('Mandar', 'mdr');
INSERT INTO languages (name, code) VALUES ('Mende', 'men');
INSERT INTO languages (name, code) VALUES ('Irish, Middle (900-1200)', 'mga');
INSERT INTO languages (name, code) VALUES ('Mi\'kmaq', 'mic');
INSERT INTO languages (name, code) VALUES ('Minangkabau', 'min');
INSERT INTO languages (name, code) VALUES ('Uncoded languages', 'mis');
INSERT INTO languages (name, code) VALUES ('Mon-Khmer (Other)', 'mkh');
INSERT INTO languages (name, code) VALUES ('Manchu', 'mnc');
INSERT INTO languages (name, code) VALUES ('Manipuri', 'mni');
INSERT INTO languages (name, code) VALUES ('Manobo languages', 'mno');
INSERT INTO languages (name, code) VALUES ('Mohawk', 'moh');
INSERT INTO languages (name, code) VALUES ('Mossi', 'mos');
INSERT INTO languages (name, code) VALUES ('Multiple languages', 'mul');
INSERT INTO languages (name, code) VALUES ('Munda languages', 'mun');
INSERT INTO languages (name, code) VALUES ('Creek', 'mus');
INSERT INTO languages (name, code) VALUES ('Mirandese', 'mwl');
INSERT INTO languages (name, code) VALUES ('Marwari', 'mwr');
INSERT INTO languages (name, code) VALUES ('Mayan languages', 'myn');
INSERT INTO languages (name, code) VALUES ('Erzya', 'myv');
INSERT INTO languages (name, code) VALUES ('Nahuatl languages', 'nah');
INSERT INTO languages (name, code) VALUES ('North American Indian', 'nai');
INSERT INTO languages (name, code) VALUES ('Neapolitan', 'nap');
INSERT INTO languages (name, code) VALUES ('Low German', 'nds');
INSERT INTO languages (name, code) VALUES ('Nepal Bhasa', 'new');
INSERT INTO languages (name, code) VALUES ('Nias', 'nia');
INSERT INTO languages (name, code) VALUES ('Niger-Kordofanian (Other)', 'nic');
INSERT INTO languages (name, code) VALUES ('Niuean', 'niu');
INSERT INTO languages (name, code) VALUES ('Nogai', 'nog');
INSERT INTO languages (name, code) VALUES ('Norse, Old', 'non');
INSERT INTO languages (name, code) VALUES ('N&#x2019;Ko', 'nqo');
INSERT INTO languages (name, code) VALUES ('Northern Sotho', 'nso');
INSERT INTO languages (name, code) VALUES ('Nubian languages', 'nub');
INSERT INTO languages (name, code) VALUES ('Classical Newari', 'nwc');
INSERT INTO languages (name, code) VALUES ('Nyamwezi', 'nym');
INSERT INTO languages (name, code) VALUES ('Nyankole', 'nyn');
INSERT INTO languages (name, code) VALUES ('Nyoro', 'nyo');
INSERT INTO languages (name, code) VALUES ('Nzima', 'nzi');
INSERT INTO languages (name, code) VALUES ('Osage', 'osa');
INSERT INTO languages (name, code) VALUES ('Turkish, Ottoman (1500-1928)', 'ota');
INSERT INTO languages (name, code) VALUES ('Otomian languages', 'oto');
INSERT INTO languages (name, code) VALUES ('Papuan (Other)', 'paa');
INSERT INTO languages (name, code) VALUES ('Pangasinan', 'pag');
INSERT INTO languages (name, code) VALUES ('Pahlavi', 'pal');
INSERT INTO languages (name, code) VALUES ('Pampanga', 'pam');
INSERT INTO languages (name, code) VALUES ('Papiamento', 'pap');
INSERT INTO languages (name, code) VALUES ('Palauan', 'pau');
INSERT INTO languages (name, code) VALUES ('Persian, Old (ca. 600-400 B.C.)', 'peo');
INSERT INTO languages (name, code) VALUES ('Philippine (Other)', 'phi');
INSERT INTO languages (name, code) VALUES ('Phoenician', 'phn');
INSERT INTO languages (name, code) VALUES ('Pohnpeian', 'pon');
INSERT INTO languages (name, code) VALUES ('Prakrit languages', 'pra');
INSERT INTO languages (name, code) VALUES ('Proven&#xE7;al, Old (to 1500)', 'pro');
INSERT INTO languages (name, code) VALUES ('Rajasthani', 'raj');
INSERT INTO languages (name, code) VALUES ('Rapanui', 'rap');
INSERT INTO languages (name, code) VALUES ('Rarotongan', 'rar');
INSERT INTO languages (name, code) VALUES ('Romance (Other)', 'roa');
INSERT INTO languages (name, code) VALUES ('Romany', 'rom');
INSERT INTO languages (name, code) VALUES ('Aromanian', 'rup');
INSERT INTO languages (name, code) VALUES ('Sandawe', 'sad');
INSERT INTO languages (name, code) VALUES ('Yakut', 'sah');
INSERT INTO languages (name, code) VALUES ('South American Indian (Other)', 'sai');
INSERT INTO languages (name, code) VALUES ('Salishan languages', 'sal');
INSERT INTO languages (name, code) VALUES ('Samaritan Aramaic', 'sam');
INSERT INTO languages (name, code) VALUES ('Sasak', 'sas');
INSERT INTO languages (name, code) VALUES ('Santali', 'sat');
INSERT INTO languages (name, code) VALUES ('Sicilian', 'scn');
INSERT INTO languages (name, code) VALUES ('Scots', 'sco');
INSERT INTO languages (name, code) VALUES ('Selkup', 'sel');
INSERT INTO languages (name, code) VALUES ('Semitic (Other)', 'sem');
INSERT INTO languages (name, code) VALUES ('Irish, Old (to 900)', 'sga');
INSERT INTO languages (name, code) VALUES ('Sign Languages', 'sgn');
INSERT INTO languages (name, code) VALUES ('Shan', 'shn');
INSERT INTO languages (name, code) VALUES ('Sidamo', 'sid');
INSERT INTO languages (name, code) VALUES ('Siouan languages', 'sio');
INSERT INTO languages (name, code) VALUES ('Sino-Tibetan (Other)', 'sit');
INSERT INTO languages (name, code) VALUES ('Slavic (Other)', 'sla');
INSERT INTO languages (name, code) VALUES ('Southern Sami', 'sma');
INSERT INTO languages (name, code) VALUES ('Sami languages (Other)', 'smi');
INSERT INTO languages (name, code) VALUES ('Lule Sami', 'smj');
INSERT INTO languages (name, code) VALUES ('Inari Sami', 'smn');
INSERT INTO languages (name, code) VALUES ('Skolt Sami', 'sms');
INSERT INTO languages (name, code) VALUES ('Soninke', 'snk');
INSERT INTO languages (name, code) VALUES ('Sogdian', 'sog');
INSERT INTO languages (name, code) VALUES ('Songhai languages', 'son');
INSERT INTO languages (name, code) VALUES ('Sranan Tongo', 'srn');
INSERT INTO languages (name, code) VALUES ('Serer', 'srr');
INSERT INTO languages (name, code) VALUES ('Nilo-Saharan (Other)', 'ssa');
INSERT INTO languages (name, code) VALUES ('Sukuma', 'suk');
INSERT INTO languages (name, code) VALUES ('Susu', 'sus');
INSERT INTO languages (name, code) VALUES ('Sumerian', 'sux');
INSERT INTO languages (name, code) VALUES ('Classical Syriac', 'syc');
INSERT INTO languages (name, code) VALUES ('Syriac', 'syr');
INSERT INTO languages (name, code) VALUES ('Tai (Other)', 'tai');
INSERT INTO languages (name, code) VALUES ('Timne', 'tem');
INSERT INTO languages (name, code) VALUES ('Tereno', 'ter');
INSERT INTO languages (name, code) VALUES ('Tetum', 'tet');
INSERT INTO languages (name, code) VALUES ('Tigre', 'tig');
INSERT INTO languages (name, code) VALUES ('Tiv', 'tiv');
INSERT INTO languages (name, code) VALUES ('Tokelau', 'tkl');
INSERT INTO languages (name, code) VALUES ('Klingon', 'tlh');
INSERT INTO languages (name, code) VALUES ('Tlingit', 'tli');
INSERT INTO languages (name, code) VALUES ('Tamashek', 'tmh');
INSERT INTO languages (name, code) VALUES ('Tonga (Nyasa)', 'tog');
INSERT INTO languages (name, code) VALUES ('Tok Pisin', 'tpi');
INSERT INTO languages (name, code) VALUES ('Tsimshian', 'tsi');
INSERT INTO languages (name, code) VALUES ('Tumbuka', 'tum');
INSERT INTO languages (name, code) VALUES ('Tupi languages', 'tup');
INSERT INTO languages (name, code) VALUES ('Altaic (Other)', 'tut');
INSERT INTO languages (name, code) VALUES ('Tuvalu', 'tvl');
INSERT INTO languages (name, code) VALUES ('Tuvinian', 'tyv');
INSERT INTO languages (name, code) VALUES ('Udmurt', 'udm');
INSERT INTO languages (name, code) VALUES ('Ugaritic', 'uga');
INSERT INTO languages (name, code) VALUES ('Umbundu', 'umb');
INSERT INTO languages (name, code) VALUES ('Undetermined', 'und');
INSERT INTO languages (name, code) VALUES ('Vai', 'vai');
INSERT INTO languages (name, code) VALUES ('Votic', 'vot');
INSERT INTO languages (name, code) VALUES ('Wakashan languages', 'wak');
INSERT INTO languages (name, code) VALUES ('Walamo', 'wal');
INSERT INTO languages (name, code) VALUES ('Waray', 'war');
INSERT INTO languages (name, code) VALUES ('Washo', 'was');
INSERT INTO languages (name, code) VALUES ('Sorbian languages', 'wen');
INSERT INTO languages (name, code) VALUES ('Kalmyk', 'xal');
INSERT INTO languages (name, code) VALUES ('Yao', 'yao');
INSERT INTO languages (name, code) VALUES ('Yapese', 'yap');
INSERT INTO languages (name, code) VALUES ('Yupik languages', 'ypk');
INSERT INTO languages (name, code) VALUES ('Zapotec', 'zap');
INSERT INTO languages (name, code) VALUES ('Blissymbols', 'zbl');
INSERT INTO languages (name, code) VALUES ('Zenaga', 'zen');
INSERT INTO languages (name, code) VALUES ('Zande languages', 'znd');
INSERT INTO languages (name, code) VALUES ('Zuni', 'zun');
INSERT INTO languages (name, code) VALUES ('Zaza', 'zza');
